### ISSUE TITLE
Issue converting response of leaderboard call to JSON

### ISSUE THREAD

**Issue by jamesheslip** [omnisnash/advent-of-code-leaderboard-microsoft-teams#2]
Hi there,

Having an issue converting the body of the response to JSON:

FetchError: invalid json response body at https://adventofcode.com/2020/leaderboard reason: Unexpected token < in JSON at position 0
    at C:\Users\james\Documents\GitHub\advent-of-code-leaderboard-microsoft-teams\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async requestJsonLeaderboard (C:\Users\james\Documents\GitHub\advent-of-code-leaderboard-microsoft-teams\src\index.js:38:26)
    at async C:\Users\james\Documents\GitHub\advent-of-code-leaderboard-microsoft-teams\src\index.js:53:29 {
  type: 'invalid-json'
}

By no means a JS wizard, but would love to get this working for my team. Any ideas?

**Comment by omnisnash** [comment]
Hello !

Can you check:

- in your `.env`, the `AOC_COOKIE` key is set and the value looks like `AOC_COOKIE=session=XXXXXXXXXXXXX`
- if the value is already set, maybe your cookie is expired (AoC website explains that the token duration 1 month). You can regenerate a brand new one by opening a browser in private navigation mode and login to your account.

Tell me if it's help !

Regards

**Comment by jamesheslip** [comment]
Thank you so much! 

I was missing the "session=" part, and just had the value of the session cookie.

**Comment by omnisnash** [comment]
I updated the README since it was not clear if we expect the full cookie or only the value, thanks for your feedback !
